name: tom_ast_generator
description: AST converter from Dart analyzer AST to serializable AST model.
version: 0.1.0
repository: https://github.com/al-the-bear/tom_d4rt
publish_to: none

environment:
  sdk: ^3.10.4

dependencies:
  analyzer: ^8.0.0
  args: ^2.4.2
  glob: ^2.1.2
  path: ^1.9.1
  yaml: ^3.1.2
  tom_d4rt_ast:
    path: ../tom_d4rt_ast
  tom_ast_model:
    path: ../tom_ast_model
  tom_build_base: ^2.5.2

dev_dependencies:
  build_runner: ^2.4.14
  tom_d4rt_generator:
    path: ../tom_d4rt_generator
  tom_d4rt_exec:
    path: ../tom_d4rt_exec
  lints: ^6.0.0
  test: ^1.25.6
