name: d4rt_generator_example
description: Example usage of the D4rt bridge generator.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.4

dependencies:
  path: ^1.9.0
  tom_d4rt_exec:
    path: ../../../tom_d4rt_exec
  tom_d4rt_generator:
    path: ../../../tom_d4rt_generator

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
