name: tom_dartscript_bridges
description: Consolidated D4rt bridges for all Tom Framework projects.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.10.4

dependencies:
  # D4rt runtime
  tom_d4rt: ^1.8.0
  
  # D4rt base REPL with dcli bridges
  tom_d4rt_dcli: ^1.0.0
  
  # Projects to bridge
  tom_core_kernel:
    path: ../../core/tom_core_kernel
  tom_core_server:
    path: ../../core/tom_core_server
  tom_build:
    path: ../../devops/tom_build
  tom_dist_ledger:
    path: ../../xternal/tom_module_distributed/tom_dist_ledger
  tom_process_monitor:
    path: ../../xternal/tom_module_distributed/tom_process_monitor
  tom_basics_network:
  
  # External packages
  dcli: ^8.4.2
  dcli_core: ^8.2.8
  dart_console: ^4.1.2
  console_markdown: ^0.0.3

dev_dependencies:
  build_runner: ^2.4.15
  lints: ^6.0.0
  test: ^1.25.6
  tom_d4rt_generator:

dependency_overrides:
  runtime_native_semaphores:
    git:
      url: https://github.com/al-the-bear/native_semaphores.git
      ref: fork-fix
