name: tom_d4rt
description: "This is a fork of D4rt (https://github.com/kodjodevf/d4rt). This just fixes the version of analyzer to 8.0.0 for now."
version: 1.3.1
repository: https://github.com/al-the-bear/tom_module_d4rt
homepage: https://github.com/al-the-bear/tom_module_d4rt
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.5.0

dependencies:
  analyzer: ^8.0.0
  pub_semver: ^2.2.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.15
